// WARNING: DO NOT EDIT. This file is Auto-Generated by AWS Mobile Hub. It will be overwritten.

// Copyright 2017-2018 Amazon.com, Inc. or its affiliates (Amazon). All Rights Reserved.
// Code generated by AWS Mobile Hub. Amazon gives unlimited permission to
// copy, distribute and modify it.

// AWS Mobile Hub Project Constants
const awsmobile = {
    'aws_app_analytics': 'enable',
    'aws_cognito_identity_pool_id': 'ap-southeast-1:00bab33e-4b80-4e28-8f32-79ced81693be',
    'aws_cognito_region': 'ap-southeast-1',
    'aws_content_delivery': 'enable',
    'aws_content_delivery_bucket': 'coralappproject-hosting-mobilehub-2068422356',
    'aws_content_delivery_bucket_region': 'ap-southeast-1',
    'aws_content_delivery_cloudfront': 'enable',
    'aws_content_delivery_cloudfront_domain': 'd2n85nxhev471r.cloudfront.net',
    'aws_mobile_analytics_app_id': '13bc41a4a49449a7adc25c525e5b1353',
    'aws_mobile_analytics_app_region': 'us-east-1',
    'aws_project_id': '62c3fc5a-0aa1-49cc-bb37-28097daed836',
    'aws_project_name': 'CoralAppProject',
    'aws_project_region': 'ap-southeast-1',
    'aws_resource_name_prefix': 'coralappproject-mobilehub-2068422356',
}

export default awsmobile;
